# SPDX-License-Identifier: AGPL-3.0-only
"""Lift the R the shipped Julia runs, feed it the test fixtures, print the answers.

Nothing here retypes the statistics: the two R bodies are read out of
`src/analysis/zero_replacement.jl` and `src/analysis/differential.jl` verbatim
and pasted into one script that webR then evaluates, with the same fixtures the
Julia tests use. check.py compares the printed answers against the independent
model in ../clr_model.py, which is where the literals in the test files came
from. `generated/out.txt` is the record.
"""
import os
import pathlib
import re
import sys

def _tools_dir():
    """Where clr_model.py and fixture.py live: $METAMANIFOLD_TOOLS, this package's
    ../tools, or the sandbox default. The harness and the model have to be run
    from the same checkout, or the comparison means nothing."""
    env = os.environ.get("METAMANIFOLD_TOOLS")
    if env:
        return pathlib.Path(env)
    here = pathlib.Path(__file__).resolve().parent
    for cand in (here.parent / "tools", pathlib.Path("/home/user/tools")):
        if (cand / "clr_model.py").is_file():
            return cand
    raise SystemExit("cannot find clr_model.py; set METAMANIFOLD_TOOLS")

REPO = pathlib.Path(os.environ.get("METAMANIFOLD_WEBUI", "/home/user/MetaManifold-WebUI"))
HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / "generated"

sys.path.insert(0, str(_tools_dir()))
import clr_model as M  # noqa: E402
import fixture as F     # noqa: E402

HAND = [[0, 2, 8], [4, 0, 6]]
ONEZERO = [[2, 8], [4, 0]]
ZEROFREE = [[1, 2, 3], [4, 5, 6]]
NEGATIVE = [[1, -1, 3], [2, 4, 1]]
ONE_ROW = [[1, 2, 3]]
SIX = [[10, 20, 0, 0], [12, 18, 0, 0], [11, 19, 3, 0], [30, 8, 0, 0], [28, 9, 0, 0], [33, 7, 0, 0]]
SIX_KEPT = [[row[0], row[1]] for row in SIX]
# What the old order replaced over: every observed taxon, the rare one included.
SIX_ALL = [row[:3] for row in SIX]
SPARSE_KEPT = [[F.SPARSE[i][j] for j in range(4)] for i in range(8)]
SPARSE_ALL = [[F.SPARSE[i][j] for j in range(11)] for i in range(8)]
DEGEN = [[1, 1], [1, 5], [2, 3], [2, 9]]
CONSTANT = [[2], [2], [2], [2]]
SINGLE = [[1], [3], [5]]

PRE = '''# generated by extract.py from the Julia sources - do not edit
# webR has no host filesystem, so run.mjs evaluates zc/R/zPatterns.R and
# zc/R/cmultRepl.R (the unmodified CRAN sources of the pinned package) into the
# global environment before this, which is what `source()` would have done.
options(digits = 17, warn = 1, useFancyQuotes = FALSE)
rc_lines <- character(0)
rc_num <- function(tag, v) {
  rc_lines <<- c(rc_lines, sprintf("%s|v|%s", tag,
    paste(sprintf("%.17g", ifelse(is.na(v), NaN, v)), collapse = " ")))
}
rc_chr <- function(tag, v) {
  rc_lines <<- c(rc_lines, sprintf("%s|v|%s", tag, paste(v, collapse = "\\x1f")))
}
'''

# cmultRepl is called as `zCompositions::cmultRepl` in the shipped source; here
# the package is only sourced, so that prefix is the single thing dropped.
REPLACE = 'da_zr_x <- x\nda_zr_delta <- %s\nda_zr_threshold <- %s\n'
WELCH = 'da_values <- z\nda_group <- grp\nda_levels <- c(%s)\n'


def body(relpath, name):
    text = (REPO / relpath).read_text()
    m = re.search(r'const %s = raw"""\n(.*?)"""\n' % re.escape(name), text, re.S)
    if not m:
        raise SystemExit("could not find %s in %s" % (name, relpath))
    return m.group(1)


def rmat(rows, name):
    flat = ", ".join(str(int(v)) for row in rows for v in row)
    return "%s <- matrix(c(%s), nrow = %d, ncol = %d, byrow = TRUE)\n" % (
        name, flat, len(rows), len(rows[0]))


def rvec(v):
    return ", ".join('"%s"' % x for x in v)


def main():
    OUT.mkdir(exist_ok=True)
    replace = body("src/analysis/zero_replacement.jl", "_REPLACE_R")
    welch = body("src/analysis/differential.jl", "_FIT_WELCH_R")
    (OUT / "replace_body.R").write_text(replace)
    (OUT / "welch_body.R").write_text(welch)
    rep = replace.replace("zCompositions::", "")

    h = [PRE]
    for name, x, delta in (("hand", HAND, 0.65), ("onezero", ONEZERO, 0.65),
                           ("sparse_kept", SPARSE_KEPT, 0.65),
                           ("sparse_all", SPARSE_ALL, 0.65),
                           ("six_kept", SIX_KEPT, 0.65),
                           ("hand_shallow", HAND, 0.05),
                           ("hand_deep", HAND, 0.99)):
        # R is run even on the table that has no zeros, which it refuses: that is
        # the message the Julia wrapper exists to avoid by not calling R at all.
        h.append("\n# --- replacement: %s ---\n%src_err <- NA_character_\n"
                 "tryCatch({%s%s%s}, error = function(e) rc_err <<- conditionMessage(e))\n"
                 "rc_chr(\"repl.%s.error\", ifelse(is.na(rc_err), \"none\", rc_err))\n"
                 "if (is.na(rc_err)) {\n"
                 "  rc_num(\"repl.%s.out\", as.vector(t(da_zr_out)))\n"
                 "  rc_num(\"repl.%s.mass\", rowSums(ifelse(x == 0, da_zr_out, 0)))\n"
                 "  rc_num(\"repl.%s.rest\", 1 - rowSums(da_zr_out))\n"
                 "  rc_num(\"repl.%s.minobs\", min(da_zr_out[x > 0]))\n"
                 "  rc_chr(\"repl.%s.positive\", ifelse(all(da_zr_out[x > 0] > 0), \"yes\", \"no\"))\n"
                 "  rc_num(\"repl.%s.dim\", dim(da_zr_out))\n"
                 "}\n"
                 % (name, rmat(x, "x"), REPLACE % (delta, 0.5), rep, "\n",
                    *(name,) * 7))
    for tag, x, delta, thr in (("zero_free", ZEROFREE, 0.65, 0.5),
                               ("negative", NEGATIVE, 0.65, 0.5),
                               ("one_row", ONE_ROW, 0.65, 0.5)):
        h.append("\n# --- the message R gives for %s ---\n%src_chr(\"msg.%s\", tryCatch({%s%s%s\n"
                 "\"none\"}, error = function(e) conditionMessage(e)))\n"
                 % (tag, rmat(x, "x"), tag, REPLACE % (delta, thr), rep, "\n"))
    for name, x, groups in (("sparse_kept", SPARSE_KEPT, F.GROUPS),
                            ("six_kept", SIX_KEPT, ["A", "A", "A", "B", "B", "B"]),
                            ("six_all", SIX_ALL, ["A", "A", "A", "B", "B", "B"]),
                            ("effect", F.EFFECT, F.EG)):
        # The same chain as differential_abundance: replace, CLR, one test per
        # taxon. The fast path (no zeros, no R) is what Julia would take, so it
        # is closed and logged here the same way.
        step = ("z <- if (any(x == 0)) {\nda_zr_x <- x\nda_zr_delta <- 0.65\n"
                "da_zr_threshold <- 0.5\n" + rep + "\n" +
                "  sweep(log(da_zr_out), 1, rowMeans(log(da_zr_out)), \"-\")\n" +
                "} else {\n  da_zr_out <- as.matrix(x / rowSums(as.matrix(x)))\n" +
                "  sweep(log(da_zr_out), 1, rowMeans(log(da_zr_out)), \"-\")\n}\n")
        h.append("\n# --- full chain: %s ---\n%s%s\ngroup <- c(%s)\n%s\n"
                 "da_values <- z\nda_group <- group\nda_levels <- c(\"A\", \"B\")\n%s\n"
                 "rc_num(\"chain.%s.estimate\", da_result$estimate)\n"
                 "rc_num(\"chain.%s.se\", da_result$se)\n"
                 "rc_num(\"chain.%s.statistic\", da_result$statistic)\n"
                 "rc_num(\"chain.%s.pvalue\", da_result$pvalue)\n"
                 "rc_num(\"chain.%s.df\", da_result$df)\n"
                 "rc_chr(\"chain.%s.status\", da_result$status)\n"
                 "rc_chr(\"chain.%s.note\", da_result$note)\n"
                 "rc_num(\"chain.%s.clr\", as.vector(t(z)))\n"
                 "rc_num(\"chain.%s.mass\", rowSums(ifelse(x == 0, da_zr_out, 0)))\n"
                 "rc_chr(\"chain.%s.columns\", names(da_result))\n"
                 "rc_num(\"chain.%s.bh\", stats::p.adjust(da_result$pvalue, method = \"BH\"))\n"
                 "rc_num(\"chain.%s.pooled\", vapply(seq_len(ncol(z)), function(j) "
                 "stats::t.test(z[group == \"B\", j], z[group == \"A\", j], "
                 "var.equal = TRUE)$p.value, numeric(1)))\n"
                 % (name, rmat(x, "x"), step, rvec(groups), "", welch,
                    *(name,) * 12))
    for name, x, groups in (("degen", DEGEN, ["A", "A", "B", "B"]),
                            ("const", CONSTANT, ["A", "A", "B", "B"]),
                            ("single", SINGLE, ["A", "A", "B"])):
        h.append("\n# --- what a fit that cannot estimate says ---\n%s\n"
                 "z <- as.matrix(x)\ngroup <- c(%s)\nda_values <- z\nda_group <- group\n"
                 "da_levels <- c(\"A\", \"B\")\n%s\n"
                 "rc_chr(\"fit.%s.status\", da_result$status)\n"
                 "rc_chr(\"fit.%s.note\", da_result$note)\n"
                 "rc_num(\"fit.%s.estimate\", da_result$estimate)\n"
                 "rc_num(\"fit.%s.pvalue\", da_result$pvalue)\n"
                 "rc_num(\"fit.%s.df\", da_result$df)\n"
                 % (rmat(x, "x"), rvec(groups), welch, *(name,) * 5))
    # webR has no MASS, so the negative-binomial path cannot be run here; it
    # is checked as text instead, which is what catches a broken or renamed
    # snippet in the shipped source.
    nb = body("src/analysis/differential.jl", "_FIT_R")
    (OUT / "fit_nb_body.R").write_text(nb)
    if "]-" in nb:
        raise SystemExit("the R raw-string delimiter appears in _FIT_R")
    lit = 'R"-[' + nb + ']-"'
    h.append("\n# --- the negative-binomial snippet has to stay parseable R ---\n"
             'rc_chr("nb_body.parse", tryCatch({parse(text = ' + lit + '); "ok"}, '
             'error = function(e) conditionMessage(e)))\n')
    (OUT / "harness.R").write_text("".join(h) + "\nrc_lines\n")
    for f in ("replace_body.R", "welch_body.R", "harness.R"):
        t = (OUT / f).read_text()
        print("  %-15s %5d lines, %6d bytes" % (f, t.count("\n"), len(t)))


if __name__ == "__main__":
    main()
